### ISSUE TITLE
Release process is broken

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/tree-sitter-bash#230]
The CI fails to prebuild binaries with the error "`Error from GitHub: Bad credentials`"

https://github.com/tree-sitter/tree-sitter-bash/actions/runs/6458399953/job/17532255266

I emailed @maxbrunsfeld about this a week ago but he hasn't responded yet.

But I also noticed that on [GitHub Releases](https://github.com/tree-sitter/tree-sitter-bash/releases) the last release is v0.20.2 from 2 weeks ago, and says there have been "105 commits to master since this release". The last release [on npm](https://www.npmjs.com/package/tree-sitter-bash?activeTab=versions) is 0.20.3 from 2 *months* ago.

And also confusingly, the Actions tab for the last two "Release" actions, the CI stops at the "Display result" step with the following output

```
Run echo "Version bump detected: "
Version bump detected: 
```

and never even makes it to the "Fail if version is lower" step.

https://github.com/tree-sitter/tree-sitter-bash/actions/runs/6477399138/job/17587534309

https://github.com/tree-sitter/tree-sitter-bash/actions/runs/6387155384/job/17335057141

What's up with that?

**Comment by verhovsky** [comment]
The GitHub API key was updated and I re-ran the jobs for v0.20.2

https://github.com/tree-sitter/tree-sitter-bash/actions/runs/6458399953/job/18120023042

and it still failed, this time with a more interesting error:

```
prebuild info build Preparing to prebuild tree-sitter-bash@0.20.2 for electron 20.0.0 on darwin-arm64 using node-gyp
gyp info find Python using Python version 3.11.5 found at "/usr/local/bin/python3"
gyp http GET https://electronjs.org/headers/v20.0.0/node-v20.0.0-headers.tar.gz
gyp http 200 https://artifacts.electronjs.org/headers/v20.0.0/node-v20.0.0-headers.tar.gz?force_headers_dist=1
gyp http GET https://electronjs.org/headers/v20.0.0/SHASUMS256.txt
gyp http 200 https://artifacts.electronjs.org/headers/v20.0.0/SHASUMS256.txt?force_headers_dist=1
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/runner/work/tree-sitter-bash/tree-sitter-bash/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/runner/work/tree-sitter-bash/tree-sitter-bash/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/runner/work/tree-sitter-bash/tree-sitter-bash/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/runner/work/tree-sitter-bash/tree-sitter-bash/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/runner/work/tree-sitter-bash/tree-sitter-bash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/tree_sitter_bash_binding/src/parser.o
../src/parser.c:15871:3: warning: variable 'eof' set but not used [-Wunused-but-set-variable]
  START_LEXER();
  ^
../src/tree_sitter/parser.h:135:8: note: expanded from macro 'START_LEXER'
  bool eof = false;             \
       ^
1 warning generated.
  CXX(target) Release/obj.target/tree_sitter_bash_binding/bindings/node/binding.o
In file included from ../bindings/node/binding.cc:2:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/node.h:69:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8.h:24:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-array-buffer.h:13:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-object.h:9:
/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-maybe.h:106:45: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
  template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
                                       ~~~~~^~~~~~~~~~~~~~~~~~~~~
                                            is_lvalue_reference
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
                            ^
In file included from ../bindings/node/binding.cc:2:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/node.h:69:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8.h:24:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-array-buffer.h:13:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-object.h:9:
/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
  template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
                                     ~~~~~^~~~~~~~~~~~~~~~~~~~~
                                          is_lvalue_reference
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:910:29: note: 'is_lvalue_reference' declared here
struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
                            ^
In file included from ../bindings/node/binding.cc:2:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/node.h:69:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8.h:24:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-array-buffer.h:13:
In file included from /var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-object.h:9:
/var/folders/3s/vfzpb5r51gs6y328rmlgzm7c0000gn/T/prebuild/electron/20.0.0/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/tree_sitter_bash_binding/bindings/node/binding.o] Error 1
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/Users/runner/work/tree-sitter-bash/tree-sitter-bash/node_modules/node-gyp/lib/build.js:203:23)
prebuild ERR! stack     at ChildProcess.emit (node:events:514:28)
prebuild ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/Users/runner/work/tree-sitter-bash/tree-sitter-bash/node_modules/node-gyp/lib/build.js:203:23)
prebuild ERR! build     at ChildProcess.emit (node:events:514:28)
prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
